# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bourbon/all/bourbon.rbi
#
# bourbon-5.0.1
module Bourbon
end
class Bourbon::Generator < Thor
end
class Bourbon::Engine < Rails::Engine
end
