# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/factory_girl_rails/all/factory_girl_rails.rbi
#
# factory_girl_rails-4.9.0
module FactoryGirlRails
end
module FactoryGirlRails::Generators
end
class FactoryGirlRails::Generators::RSpecGenerator
  def factory_girl_directory; end
  def fixture_replacement_setting; end
  def initialize(generators); end
  def run; end
end
class FactoryGirlRails::Generators::NonRSpecGenerator
  def initialize(generators); end
  def run; end
  def test_framework; end
end
class FactoryGirlRails::Generators::NullGenerator
  def initialize(generators); end
  def run; end
end
class FactoryGirlRails::Generator
  def factory_girl_disabled?; end
  def generator; end
  def initialize(config); end
  def rails_options; end
  def run; end
  def test_framework; end
end
module FactoryGirl
end
class FactoryGirl::Railtie < Rails::Railtie
end
