# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flutie/all/flutie.rbi
#
# flutie-2.2.0
module Flutie
end
class Flutie::BodyClass
  def action_name; end
  def action_part; end
  def basic_body_class; end
  def controller; end
  def controller_part; end
  def controller_path; end
  def extra_body_classes_symbol; end
  def initialize(options, controller); end
  def options; end
  def qualified_controller_name; end
end
module BodyClassHelper
  def body_class(options = nil); end
end
class Flutie::PageTitle
  def app_name; end
  def initialize(options); end
  def options; end
  def page_title_symbol; end
  def rails_app_name; end
  def separator; end
end
class Flutie::PageTitlePresenter
  def app_name; end
  def content; end
  def initialize(app_name, content, separator, reversed = nil); end
  def ordered_parts; end
  def reversed; end
  def reversed_order?; end
  def separator; end
  def to_s; end
end
module PageTitleHelper
  def page_title(options = nil); end
end
class Flutie::Railtie < Rails::Railtie
end
