# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/formulaic/all/formulaic.rbi
#
# formulaic-0.4.1
module Formulaic
  def self.configure; end
  def self.default_wait_time; end
  def self.default_wait_time=(arg0); end
end
class Formulaic::InputNotFound < StandardError
end
class Formulaic::OptionForSelectInputNotFound < StandardError
end
class Formulaic::Label
  def action; end
  def attribute; end
  def class_exists?(class_name); end
  def human_attribute_name; end
  def initialize(model_name, attribute, action); end
  def lookup_paths; end
  def model_name; end
  def to_s; end
  def to_str; end
  def translate; end
end
module Formulaic::Inputs
end
class Formulaic::Inputs::Input
  def initialize(label, value); end
  def label; end
  def label=(arg0); end
  def value; end
  def value=(arg0); end
  include Capybara::DSL
end
class Formulaic::Inputs::CheckboxInput < Formulaic::Inputs::ArrayInput
  def check_boxes; end
  def checkbox_labels; end
  def checkbox_labels_selector; end
  def checkbox_name_selector; end
  def checkbox_name_selector_for_association; end
  def fill; end
  def has_check_boxes?; end
end
class Formulaic::Inputs::SelectInput < Formulaic::Inputs::ArrayInput
  def fill; end
  def has_multiple_select?; end
  def has_select?; end
  def select_element; end
  def select_is_multiple?; end
  def select_options; end
end
class Formulaic::Inputs::ArrayInput < Formulaic::Inputs::Input
  def attempt_to_fill_checkboxes; end
  def attempt_to_fill_selects; end
  def contains_all_options?(nodes); end
  def fill; end
  def raise_input_error; end
end
class Formulaic::Inputs::BooleanInput < Formulaic::Inputs::Input
  def fill; end
end
class Formulaic::Inputs::DateInput < Formulaic::Inputs::Input
  def fill; end
  def select_date(date, options); end
end
class Formulaic::Inputs::DateTimeInput < Formulaic::Inputs::DateInput
  def fill; end
  def select_date(date_time, options); end
end
class Formulaic::Inputs::StringInput < Formulaic::Inputs::Input
  def fill; end
  def has_option_in_select?(option, select); end
  def lookup_paths_for_option; end
  def translate_option(option); end
end
class Formulaic::Inputs::FileInput < Formulaic::Inputs::Input
  def fill; end
end
class Formulaic::Form
  def action; end
  def build_input(model_name, field, value); end
  def build_inputs(model_name, attributes); end
  def fill; end
  def initialize(model_name, action, attributes); end
  def input_class_for(value); end
  def inputs; end
  def model_name; end
end
class Formulaic::Form::InvalidAttributeTypeError < StandardError
end
module Formulaic::Dsl
  def fill_form(model_name, action = nil, attributes); end
  def fill_form_and_submit(model_name, action = nil, attributes); end
  def input(model_name, field, action = nil); end
  def submit(model_class, action = nil); end
end
