# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-canonical-host/all/rack-canonical-host.rbi
#
# rack-canonical-host-0.2.3
module Rack
end
class Rack::CanonicalHost
  def app; end
  def app=(arg0); end
  def block; end
  def block=(arg0); end
  def call(env); end
  def evaluate_host(env); end
  def host; end
  def host=(arg0); end
  def initialize(app, host = nil, options = nil, &block); end
  def options; end
  def options=(arg0); end
end
class Rack::CanonicalHost::Redirect
  def any_match?(patterns, string); end
  def cache_control; end
  def cache_control=(arg0); end
  def canonical?; end
  def conditions; end
  def conditions=(arg0); end
  def enabled?; end
  def env; end
  def env=(arg0); end
  def headers; end
  def host; end
  def host=(arg0); end
  def ignore; end
  def ignore=(arg0); end
  def ignored?; end
  def initialize(env, host, options = nil); end
  def known?; end
  def new_url; end
  def request_uri; end
  def response; end
end
