# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_real_favicon/all/rails_real_favicon.rbi
#
# rails_real_favicon-0.0.13
module RailsRealFavicon
end
