# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/readingtime/all/readingtime.rbi
#
# readingtime-0.4.0
class String
  def calculate_size; end
  def reading_time(options = nil); end
end
module Readingtime
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
  def self.format_approx(seconds); end
  def self.format_full(hms); end
  def self.format_seconds(seconds); end
  def self.format_words(seconds); end
  def self.hms(secs); end
  def self.minutes_in_seconds(words); end
  def self.reading_speed; end
  def self.seconds(words); end
end
class Readingtime::Calculator
  def calculate_size(words); end
  def format_approx(seconds); end
  def format_full(hms); end
  def format_seconds(seconds); end
  def format_words(seconds); end
  def hms(secs); end
  def initialize(opts = nil); end
  def minutes_in_seconds(words); end
  def reading_speed; end
  def reading_time(words, opts = nil); end
  def seconds(words); end
end
class Readingtime::Configuration
  def initialize; end
  def reading_speed; end
  def reading_speed=(arg0); end
end
