# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/recipient_interceptor/all/recipient_interceptor.rbi
#
# recipient_interceptor-0.2.0
class RecipientInterceptor
  def add_custom_headers(message); end
  def add_subject_prefix(message); end
  def delivering_email(message); end
  def initialize(recipients, options = nil); end
  def normalize_to_array(recipients); end
end
