# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby_http_client/all/ruby_http_client.rbi
#
# ruby_http_client-3.3.0
module SendGrid
end
class SendGrid::Response
  def body; end
  def headers; end
  def initialize(response); end
  def parsed_body; end
  def status_code; end
end
class SendGrid::Client
  def _(name = nil); end
  def add_ssl(http); end
  def add_version(url = nil); end
  def build_args(args); end
  def build_query_params(url, query_params); end
  def build_request(name, args); end
  def build_request_headers(request); end
  def build_url(query_params: nil); end
  def host; end
  def http; end
  def initialize(host: nil, request_headers: nil, version: nil, url_path: nil); end
  def make_request(http, request); end
  def method_missing(name, *args, &_block); end
  def request; end
  def request_headers; end
  def update_headers(request_headers); end
  def url_path; end
end
