# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:mailers to regenerate.
class ClearanceMailer
  sig { params(user: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.change_password(user); end
end
